//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadevyat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вход гостя.
    /// </summary>
    // *** Start programmer edit section *** (ВходГостя CustomAttributes)

    // *** End programmer edit section *** (ВходГостя CustomAttributes)
    [AutoAltered()]
    [Caption("Вход гостя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходГостяE", new string[] {
            "РегистрГостя.Гость as \'Гость\'",
            "РегистрГостя.Гость.ФИО as \'ФИО\'",
            "РегистрГостя.Карта.КодКарты as \'Номер карты\'"})]
    public class ВходГостя : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probadevyat.РегистрГостя fРегистрГостя;
        
        private IIS.Probadevyat.РегистрацВхода fРегистрацВхода;
        
        // *** Start programmer edit section *** (ВходГостя CustomMembers)

        // *** End programmer edit section *** (ВходГостя CustomMembers)

        
        /// <summary>
        /// Вход гостя.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.РегистрГостя CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.РегистрГостя CustomAttributes)
        [PropertyStorage(new string[] {
                "РегистрГостя"})]
        [NotNull()]
        public virtual IIS.Probadevyat.РегистрГостя РегистрГостя
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрГостя Get start)

                // *** End programmer edit section *** (ВходГостя.РегистрГостя Get start)
                IIS.Probadevyat.РегистрГостя result = this.fРегистрГостя;
                // *** Start programmer edit section *** (ВходГостя.РегистрГостя Get end)

                // *** End programmer edit section *** (ВходГостя.РегистрГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрГостя Set start)

                // *** End programmer edit section *** (ВходГостя.РегистрГостя Set start)
                this.fРегистрГостя = value;
                // *** Start programmer edit section *** (ВходГостя.РегистрГостя Set end)

                // *** End programmer edit section *** (ВходГостя.РегистрГостя Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probadevyat.РегистрацВхода.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.РегистрацВхода CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.РегистрацВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РегистрацВхода"})]
        public virtual IIS.Probadevyat.РегистрацВхода РегистрацВхода
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрацВхода Get start)

                // *** End programmer edit section *** (ВходГостя.РегистрацВхода Get start)
                IIS.Probadevyat.РегистрацВхода result = this.fРегистрацВхода;
                // *** Start programmer edit section *** (ВходГостя.РегистрацВхода Get end)

                // *** End programmer edit section *** (ВходГостя.РегистрацВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрацВхода Set start)

                // *** End programmer edit section *** (ВходГостя.РегистрацВхода Set start)
                this.fРегистрацВхода = value;
                // *** Start programmer edit section *** (ВходГостя.РегистрацВхода Set end)

                // *** End programmer edit section *** (ВходГостя.РегистрацВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходГостяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходГостяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходГостяE", typeof(IIS.Probadevyat.ВходГостя));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВходГостя.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)
    public class DetailArrayOfВходГостя : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probadevyat.DetailArrayOfВходГостя members)

        // *** End programmer edit section *** (IIS.Probadevyat.DetailArrayOfВходГостя members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВходГостя by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВходГостя.
        /// </summary>
        public DetailArrayOfВходГостя(IIS.Probadevyat.РегистрацВхода fРегистрацВхода) : 
                base(typeof(ВходГостя), ((ICSSoft.STORMNET.DataObject)(fРегистрацВхода)))
        {
        }
        
        public IIS.Probadevyat.ВходГостя this[int index]
        {
            get
            {
                return ((IIS.Probadevyat.ВходГостя)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probadevyat.ВходГостя dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
