//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadevyat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр гостя.
    /// </summary>
    // *** Start programmer edit section *** (РегистрГостя CustomAttributes)

    // *** End programmer edit section *** (РегистрГостя CustomAttributes)
    [AutoAltered()]
    [Caption("Регистрация гостя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрГостяE", new string[] {
            "Дата as \'Дата\'",
            "Гость as \'Гость\'",
            "Гость.ФИО as \'ФИО\'",
            "Карта as \'Карта\'",
            "Карта.КодКарты as \'Код карты\'",
            "Карта.Комната.НомерКомнаты as \'Комната\'",
            "Сотрудник as \'Ответственный\'",
            "Сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Гость.ФИО",
            "Карта.КодКарты",
            "Сотрудник.ФИО"})]
    [MasterViewDefineAttribute("РегистрГостяE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("РегистрГостяE", "Карта", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [MasterViewDefineAttribute("РегистрГостяE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("РегистрГостяL", new string[] {
            "Дата as \'Дата\'",
            "Гость.ФИО as \'ФИО\'",
            "Карта.КодКарты as \'Код карты\'",
            "Карта.Комната.НомерКомнаты as \'Комната\'",
            "Сотрудник.ФИО as \'Ответственный\'"})]
    public class РегистрГостя : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Probadevyat.Гость fГость;
        
        private IIS.Probadevyat.Сотрудник fСотрудник;
        
        private IIS.Probadevyat.Карта fКарта;
        
        // *** Start programmer edit section *** (РегистрГостя CustomMembers)

        // *** End programmer edit section *** (РегистрГостя CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегистрГостя.Дата CustomAttributes)

        // *** End programmer edit section *** (РегистрГостя.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегистрГостя.Дата Get start)

                // *** End programmer edit section *** (РегистрГостя.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегистрГостя.Дата Get end)

                // *** End programmer edit section *** (РегистрГостя.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрГостя.Дата Set start)

                // *** End programmer edit section *** (РегистрГостя.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегистрГостя.Дата Set end)

                // *** End programmer edit section *** (РегистрГостя.Дата Set end)
            }
        }
        
        /// <summary>
        /// Регистр гостя.
        /// </summary>
        // *** Start programmer edit section *** (РегистрГостя.Гость CustomAttributes)

        // *** End programmer edit section *** (РегистрГостя.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Probadevyat.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (РегистрГостя.Гость Get start)

                // *** End programmer edit section *** (РегистрГостя.Гость Get start)
                IIS.Probadevyat.Гость result = this.fГость;
                // *** Start programmer edit section *** (РегистрГостя.Гость Get end)

                // *** End programmer edit section *** (РегистрГостя.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрГостя.Гость Set start)

                // *** End programmer edit section *** (РегистрГостя.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (РегистрГостя.Гость Set end)

                // *** End programmer edit section *** (РегистрГостя.Гость Set end)
            }
        }
        
        /// <summary>
        /// Регистр гостя.
        /// </summary>
        // *** Start programmer edit section *** (РегистрГостя.Карта CustomAttributes)

        // *** End programmer edit section *** (РегистрГостя.Карта CustomAttributes)
        [PropertyStorage(new string[] {
                "Карта"})]
        [NotNull()]
        public virtual IIS.Probadevyat.Карта Карта
        {
            get
            {
                // *** Start programmer edit section *** (РегистрГостя.Карта Get start)

                // *** End programmer edit section *** (РегистрГостя.Карта Get start)
                IIS.Probadevyat.Карта result = this.fКарта;
                // *** Start programmer edit section *** (РегистрГостя.Карта Get end)

                // *** End programmer edit section *** (РегистрГостя.Карта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрГостя.Карта Set start)

                // *** End programmer edit section *** (РегистрГостя.Карта Set start)
                this.fКарта = value;
                // *** Start programmer edit section *** (РегистрГостя.Карта Set end)

                // *** End programmer edit section *** (РегистрГостя.Карта Set end)
            }
        }
        
        /// <summary>
        /// Регистр гостя.
        /// </summary>
        // *** Start programmer edit section *** (РегистрГостя.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (РегистрГостя.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Probadevyat.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (РегистрГостя.Сотрудник Get start)

                // *** End programmer edit section *** (РегистрГостя.Сотрудник Get start)
                IIS.Probadevyat.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (РегистрГостя.Сотрудник Get end)

                // *** End programmer edit section *** (РегистрГостя.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрГостя.Сотрудник Set start)

                // *** End programmer edit section *** (РегистрГостя.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (РегистрГостя.Сотрудник Set end)

                // *** End programmer edit section *** (РегистрГостя.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрГостяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрГостяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрГостяE", typeof(IIS.Probadevyat.РегистрГостя));
                }
            }
            
            /// <summary>
            /// "РегистрГостяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрГостяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрГостяL", typeof(IIS.Probadevyat.РегистрГостя));
                }
            }
        }
    }
}
